- hosts: all
  become: yes
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: present
    - name: copy code to remote machine
      copy:
        src: index.html
        dest: /var/www/html/
    - name: start apache
      service:
        name: httpd
        enabled: yes
        state: started
